config/routes.rb
MyAuthonticationSample::Application.routes.draw do
  resources :item
  devise_for :users
  resources :dashboard
  root :to => "home#index"
   post '/hide_item/:id',  to: 'item#only_hide' #edited after inserting the code of Ajax
   resources :roles

  

end

app/models/ability.rb
class Ability
  include CanCan::Ability
  def initialize(user)
    user.role.permissions.each do |permission|
      if permission.subject_class == "all"
        can permission.action.to_sym, permission.subject_class.to_sym
      else
        can permission.action.to_sym, permission.subject_class.constantize
      end
    #can :show,Item
    end         
  end
end

  # def initialize(user)
  #   # Define abilities for the passed in user here. For example:
    
  #      user ||= User.new # guest user (not logged in)
  #       # if user.role == "admin" 
  #       #    can :manage, :all
  #       # end        
  #       #  if user.role != "admin" 
  #       #     can :read, :all
  #       # end

  #       can :manage, :all if user.role == "admin"
  #       can :read, :all if (user.role != "admin" || user.role==nil)
  #       if user.role == "broker" 
  #           can :read, :all
  #           can :create, :all
  #           #can :only_hide,:all 
  #       end
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  

app/models/address.rb
class Address < ActiveRecord::Base
	 belongs_to :item , foreign_key: 'item_id'#, primary_key: :id

end

app/models/item.rb
class Item < ActiveRecord::Base
	
	has_one :address, dependent: :destroy
	belongs_to :user
	before_create :default_values
	private
	def default_values
    	 self.removed = false

    	 nil
    end
end

app/models/permission.rb
class Permission < ActiveRecord::Base
	# attr_accessible :subject_class, :action, :name
end

app/models/role.rb
class Role < ActiveRecord::Base
  #attr_accessible :name

  has_many :users
  has_and_belongs_to_many :permissions
  validates :name, presence: true, uniqueness: true

  def set_permissions(permissions)
  permissions.each do |id|
    #find the main permission assigned from the UI
    permission = Permission.find(id)
    self.permissions << permission
  end
end
end

app/models/user.rb
class User < ActiveRecord::Base
	#has_and_belongs_to_many :roles
	#has_one :role
	has_many :items
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

 belongs_to :role
 def super_admin?
  self.role.name == "Super Admin"
 end
  # ROLES = %w[admin moderator author banned]
  # def role?(base_role)
  # 	ROLES.index(base_role.to_s) <= ROLES.index(role)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  rescue_from CanCan::AccessDenied do |exception|
    flash[:alert] = "Access denied. You are not authorized to access the requested page."
    #redirect_to root_path and return
    redirect_to dashboard_index_path #and return
  end
  #this before filter is for solving the problem of parameter overriden occurred because of the params.
	before_filter do
	resource = controller_name.singularize.to_sym
	method = "#{resource}_params"
	params[resource] &&= send(method) if respond_to?(method, true)
	end

  protected
  #derive the model name from the controller. egs UsersController will return User
  def self.permission
    return name = self.name.gsub('Controller','').singularize.split('::').last.constantize.name rescue nil
  end
 
  def current_ability
    @current_ability ||= Ability.new(current_user)
  end
 
  #load the permissions for the current user so that UI can be manipulated
  def load_permissions    
      @current_permissions = current_user.role.permissions.collect{|i| [i.subject_class, i.action]}    
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	before_filter :authenticate_user!
	#current_user
	#load_and_authorize_resource
	before_filter :load_permissions # call this after load_and_authorize else it gives a cancan error

	def index
		#@item = current_user.items
		#redirect_to :controller => 'dashboard', :action => 'show'
	end
	def show
		#redirect_to :controller => 'item', :action => 'index'
		
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
 #before_filter :authenticate_user!
 #current_user
 #load_and_authorize_resource
#before_filter :load_permissions # call this after load_and_authorize else it gives a cancan error

 def index
		if user_signed_in?
			redirect_to :controller => 'dashboard', :action => 'index'
		end
	end
end

app/controllers/item_controller.rb
class ItemController < ApplicationController
	before_filter :authenticate_user!
	load_and_authorize_resource
	before_filter :load_permissions # call this after load_and_authorize else it gives a cancan error

	def index
		@item = current_user.items

	end
	##########################
	def new
		@item = Item.new
		@address = Address.new
	end
	#########################
	def create
		
		@item = Item.new(item_params)
		@item.user = current_user
		@item.save
		@address = @item.build_address(address_params)
		@address.save
		redirect_to @item
		
    end
	##########################
	def show
		#params.inspect
		@item = current_user.items.find(params[:id])
	    # @item  = Item.find(params[:id])
	     @address = @item.address
        
	end
	##########################
	def destroy
		@item = Item.find(params[:id])
		@item.delete
		redirect_to Item
	end
	##########################
    def only_hide
        @item = Item.find(params[:id])
        @item.removed = true
        @item.save
        #render :nothing => true
        render :text => "Done!"
    end
    ###########################
	private
	def item_params
		params.require(:item).permit(:listingtype, :price, :purpose, :area, :description, :address_id)
	end
	
	private
	def address_params
		params.require(:address).permit(:country, :city, :community, :subcommunity, :subtype)
	end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_filter :authenticate_user!
  #before_filter :is_super_admin?
  load_and_authorize_resource
  before_filter :load_permissions # call this after load_and_authorize else it gives a cancan error

  def index
    #you dont want to set the permissions for Super Admin.
    @roles = Role.all.keep_if{|i| i.name != "Super Admin"}
  end
 
  def show
    @role = Role.find(params[:id])
    @permissions = @role.permissions
  end
 
  def edit
    @role = Role.find(params[:id])
    #we dont want the Drawing permissions to be displayed.
    #this way u can display only selected models. you can choose which methods u want to display too.
    #@permissions = Permission.all.keep_if{|i| ["Item"].include? i.subject_class}.compact
    @permissions = Permission.all
    @role_permissions = @role.permissions.collect{|p| p.id}
  end
 
  def update
    @role = Role.find(params[:id])
    @role.permissions = []
    @role.set_permissions(params[:permissions]) if params[:permissions]
    #require 'debugger'; debugger
    if @role.save
      redirect_to roles_path and return
    end
    #@permissions = Permission.all.keep_if{|i| ["Item"].include? i.subject_class}.compact
    @permissions = Permission.all
    render 'edit'
  end
 
  private
 
  def is_super_admin?
    redirect_to dashboard_index_path and return unless current_user == "Admin"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/item_helper.rb
module ItemHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/dashboard/index.html.erb
<h2> welcome to ur account </h2>
<p><%= link_to "Items listings" , item_index_path %></p>
<p><%= link_to "Add new Item" , roles_path if can? :index, Role %></p>

app/views/home/index.html.erb
<h2> welcome to our website </h2>

app/views/item/index.html.erb
<h1>Listing Items </h1>
<%= link_to "Add New Item" , new_item_path if can? :create, Item %>
<% @item.each do |i| %>
   <% if i.removed == false %>
  <p> <%= i.listingtype %>  
   | <%= link_to "Show this item" , item_path(i)  if can? :show, Item %> | 
   <div class="delete">
     <%= link_to "Delete" if can? :only_hide, Item %> 
   </div>
   <input type = "hidden" value = "<%= i.id %>"  class = "id" >
  </p>
<p><%= link_to "back to dashboard" , dashboard_index_path %></p>
   <% end %>
<% end %>
<script>
$(document).ready(function()
{
   $(".delete").click(function()
   {
      console.log($(this).next().val())
      var url = "/hide_item/" + $(this).next().val()
      $(this).hide(); 
      $.post(url);

    });
});
</script>

app/views/item/new.html.erb
<h1>Welcome in New Item page</h1>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= form_for @item, url: item_index_path do |f| %>
  

  <div class="field" >
    <%= f.label :listingtype, "Listing Type:"%><br />
    <%= f.text_field :listingtype %>
  </div>
  <div class="field">
    <%= f.label :price, "Price" %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :purpose, "Purpose" %><br />
    <%= f.text_field :purpose %>
  </div>
  <div class="field">
    <%= f.label :area, "Area" %><br />
    <%= f.text_field :area %>
  </div>
  <div class="field">
    <%= f.label :description, "Description" %><br />
    <%= f.text_area :description %>
  </div>
 <%= fields_for @address do |c| %>
    
  <div class="field" >
    <%= c.label :country, "country:"%><br />
    <%= c.text_field :country %>
  </div>
  <div class="field">
    <%= c.label :city, "city" %><br />
    <%= c.text_field :city %>
  </div>
  <div class="field">
    <%= c.label :community, "community" %><br />
    <%= c.text_field :community %>
  </div>
  <div class="field">
    <%= c.label :subcommunity, "subcommunity" %><br />
    <%= c.text_field :subcommunity %>
  </div>
  <div class="field">
    <%= c.label :subtype, "subtype" %><br />
    <%= c.text_field :subtype %>
  </div>
  
  <% end %>
<div class="action">
    <%= f.submit "Create" %><br />
  </div>
<% end %>

app/views/item/show.html.erb
<h1>Hello In Show Page </h1>

<p>
  <b>Listing Type:</b>
  <%= @item.listingtype %>
</p>
<p>
  <b>Price</b>
  <%= @item.price %>
</p>
<p>
  <b>Purpose</b>
  <%= @item.purpose %>
</p>
<p>
  <b>Area</b>
  <%= @item.area %>
</p>
<p>
  <b>country</b>
  <%= @address.country %>
</p>

<p>
  <b>city</b>
  <%= @address.city %>
</p>
<p>
  <b>community</b>
  <%= @address.community %>
</p>
<p>
  <b>subcommunity</b>
  <%= @address.subcommunity %>
</p>
<p>
  <b>subtype</b>
  <%= @address.subtype %>
</p>
<p>
  <b>Description</b>
  <%= @item.description %>
</p>
<p><%= link_to "back to dashboard" , dashboard_index_path %> | <%= link_to "back to items" , item_index_path %></p> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyAuthonticationSample</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if user_signed_in? %>
  <p>Logged in as <strong><%= current_user.email %></strong>
    . and your role is : <strong>
    <% if (current_user.role == nil ) %>
    visitor
    <% else %>
    <%= current_user.role.name %>
    <% end %> </strong> </p>
<br>
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>

<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
	
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/roles/edit.html.erb
<div class="row">
	<div class="span16">
		<%= form_for  @role, :url => role_path, :method => :put  do |f| %>
		<fieldset>
			<legend> Role </legend>
			<br>
			<%= @role.name %>
			<br>
			Permissions
			<br>
			<table border="1" style="width:300px; border-collapse:collapse;">
				<tr>
					<th> Class </th>
					<th> Action </th>
					<th> Description </th>
					<th> <%= check_box_tag 'main', 0, false %> </th>
				</tr>
				<% @permissions.each do |permission| %>
				<tr>
					<td><%= permission.subject_class %> </td>
					<td><%= permission.action %> </td>
					<td><%= permission.description %> </td>
					<td> <center><%= check_box_tag 'permissions[]', permission.id, @role_permissions.include?(permission.id), {array: true, class: "check_box"} %> </center></td> 
				</tr>
				<% end %>
			</table>
			<div>
				<div>
					<br>
					<%= f.submit "Update" %>
					<%= link_to 'Cancel', roles_path %>
				</div>
			</div>
		<% end %>
		</fieldset>
	</div>
</div>

app/views/roles/index.html.erb
<h1> Listing Roles </h1>

 <% @roles.each do |role| %>
<p><%= role.name %> |
 <%= link_to 'show', role %> |
 <%= link_to 'edit', edit_role_path(role) %> </p>

<% end %>

app/views/roles/show.html.erb
<h1> <%= @role.name %> </h1>

<table border="1" style="width:300px; border-collapse:collapse;">
	<tr>
		<th> Class </th>
		<th> Action </th>
	</tr>
	<% @permissions.each do |permission| %>
	<tr>
		<td><%= permission.subject_class %> </td>
		<td><%= permission.action %> </td>
	</tr>
	<% end %>
</table> 
<br/>
<%= link_to 'back', roles_path %>